/**
 * 角色定义
 */
export const roles = [
  { id: "all", name: "全部资源", icon: "🎯" },
  { id: "rd", name: "研发创新", icon: "🧪" },
  { id: "quality", name: "质量合规", icon: "⚖️" },
  { id: "clinical", name: "临床研究", icon: "🏥" },
  { id: "production", name: "生产制造", icon: "🏭" },
  { id: "reg", name: "注册申报", icon: "📝" },
  { id: "it", name: "数字信息化", icon: "💻" },
  { id: "market", name: "市场准入", icon: "📊" },
  { id: "medical", name: "医学事务", icon: "🩺" },
  { id: "pv", name: "药物警戒", icon: "🛡️" },
  { id: "scm", name: "供应链", icon: "📦" },
  { id: "intelligence", name: "行业情报", icon: "🔍" },
];

/**
 * 卡片数据
 */
export const cardData = [
  // ==========================================
  // 1. 专业管理系统 (Professional Systems)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=medidata.com&sz=128",
    brand: "Medidata",
    name: "临床试验管理系统",
    description: "全面管理临床试验数据，提供电子数据采集 (EDC)、随机化、药物编盲、受试者管理等完整功能，确保数据质量和合规性。",
    tags: ["临床试验", "数据管理", "EDC"],
    url: "https://www.medidata.com",
    roles: ["clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=vault.com&sz=128",
    brand: "Veeva Vault",
    name: "生命科学云平台",
    description: "行业领先的监管合规与内容管理平台，涵盖临床、质量、监管和医学事务，确保符合 FDA、EMA 等监管要求。",
    tags: ["合规", "文档管理", "QMS"],
    url: "https://www.veeva.com",
    roles: ["quality", "reg", "clinical", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=mastercontrol.com&sz=128",
    brand: "MasterControl",
    name: "质量管理系统 (QMS)",
    description: "全面的质量控制解决方案，涵盖 CAPA、偏差管理、变更控制、审计及文档管理，满足 GMP、ISO 等体系要求。",
    tags: ["质量管理", "合规", "QMS"],
    url: "https://www.mastercontrol.com",
    roles: ["quality", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=spartasystems.com&sz=128",
    brand: "TrackWise",
    name: "数字化质量管理平台",
    description: "Honeywell 旗下的全球领先 QMS 解决方案，通过自动化流程提升合规性，广泛应用于全球顶尖药企。",
    tags: ["QMS", "质量管理", "合规"],
    url: "https://www.spartasystems.com/trackwise-digital/",
    roles: ["quality", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=idbs.com&sz=128",
    brand: "IDBS",
    name: "研发数据管理平台",
    description: "提供 E-WorkBook 等电子实验记录系统，支持生物制药研发全生命周期的数据采集、分析与合规存储。",
    tags: ["ELN", "数据科学", "研发管理"],
    url: "https://www.idbs.com",
    roles: ["rd", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=dotmatics.com&sz=128",
    brand: "Dotmatics",
    name: "科学智能与研发协作",
    description: "端到端的科学数据管理平台，整合了化合物管理、生物分析和工作流自动化，助力加速科学发现过程。",
    tags: ["科学数据", "研发协作", "IT工具"],
    url: "https://www.dotmatics.com",
    roles: ["rd", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=labware.com&sz=128",
    brand: "LabWare",
    name: "实验室信息管理系统",
    description: "LIMS 领域的标杆，全面管理实验室流程、样本、仪器集成和数据，确保数据质量和 GLP 可追溯性。",
    tags: ["实验室管理", "LIMS", "质量控制"],
    url: "https://www.labware.com",
    roles: ["rd", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=siemens.com&sz=128",
    brand: "Siemens",
    name: "智能制造平台",
    description: "智能化生产制造管理平台，集成 MES、SCADA、ERP，实现生产计划优化、设备监控、批次管理，确保 GMP 合规。",
    tags: ["智能制造", "MES", "生产管理"],
    url: "https://www.siemens.com/global/en/products/automation/industry-software.html",
    roles: ["production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=emerson.com&sz=128",
    brand: "Emerson Syncade",
    name: "制造执行系统 (MES)",
    description: "专为制药和生物技术设计的 MES，支持电子批记录 (EBR) 和实时质量发布，显著提升生产合规性与效率。",
    tags: ["MES", "数字化生产", "GMP"],
    url: "https://www.emerson.com/en-us/automation/operations-management/syncade",
    roles: ["production", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=emerson.com&sz=128",
    brand: "Emerson DeltaV",
    name: "分布式控制系统 (DCS)",
    description: "高度自动化的生产控制系统，广泛应用于生物制药的上游发酵和下游纯化工艺，确保批次一致性。",
    tags: ["DCS", "自动化控制", "生产过程"],
    url: "https://www.emerson.com/en-us/automation/deltav",
    roles: ["production", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=iqvia.com&sz=128",
    brand: "IQVIA OCE",
    name: "医药客户关系管理 (CRM)",
    description: "基于云端的全渠道营销平台，整合了 CRM、活动管理和内容投放，助力药企建立精准的医生互动体系。",
    tags: ["CRM", "市场营销", "全渠道"],
    url: "https://www.iqvia.com/solutions/commercial-operations/oce",
    roles: ["market", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=sap.com&sz=128",
    brand: "SAP",
    name: "企业资源规划 (ERP)",
    description: "全球领先的 ERP 系统，优化制药企业的供应链、财务 and 生产流程，实现端到端的业务可视化与合规管理。",
    tags: ["ERP", "供应链", "生产管理"],
    url: "https://www.sap.com/products/scm.html",
    roles: ["production", "scm", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=werum.com&sz=128",
    brand: "Werum PAS-X",
    name: "制药 MES 系统",
    description: "专为生物制药设计的制造执行系统，实现电子批记录 (EBR) 管理，确保生产过程的完整合规性。",
    tags: ["MES", "电子批记录", "GMP"],
    url: "https://www.werum.com",
    roles: ["production", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=oracle.com&sz=128",
    brand: "Oracle Argus",
    name: "药物警戒系统",
    description: "全球领先的不良事件管理平台，支持安全性数据的收集、评估、信号检测和向全球监管机构提交报告。",
    tags: ["PV", "药物警戒", "安全监测"],
    url: "https://www.oracle.com/industries/life-sciences/safety",
    roles: ["pv", "clinical", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=viedoc.com&sz=128",
    brand: "Viedoc",
    name: "电子数据采集系统",
    description: "现代化的 EDC 系统，支持临床试验数据的在线采集、管理 and 质量控制，提升数据透明度并满足 GCP 要求。",
    tags: ["临床试验", "EDC", "数据管理"],
    url: "https://www.viedoc.com",
    roles: ["clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=valgenesis.com&sz=128",
    brand: "ValGenesis",
    name: "验证管理系统 (VLMS)",
    description: "数字化的验证生命周期管理，涵盖设备、工艺 and 软件验证，确保符合 GAMP 5 和 GMP 标准。",
    tags: ["验证", "合规", "质量管理"],
    url: "https://www.valgenesis.com",
    roles: ["quality", "production", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=benchling.com&sz=128",
    brand: "Benchling",
    name: "现代生物研发平台",
    description: "云端生物实验室平台，集成了电子实验记录本 (ELN)、分子生物学设计、库存管理和工作流管理。",
    tags: ["ELN", "生信工具", "研发管理"],
    url: "https://www.benchling.com",
    roles: ["rd", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=labvantage.com&sz=128",
    brand: "LabVantage",
    name: "现代化 LIMS 平台",
    description: "高度可配置的实验室系统，支持从早期研发到质量控制的全流程管理，助力实验室数字化转型。",
    tags: ["LIMS", "实验室数字化", "质量管理"],
    url: "https://www.labvantage.com",
    roles: ["quality", "rd", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=auditboard.com&sz=128",
    brand: "AuditBoard",
    name: "审计管理系统",
    description: "一体化的审计、风险和合规管理平台，自动跟踪审计发现 and 整改进度，提升企业内部治理水平。",
    tags: ["审计", "合规", "风险管理"],
    url: "https://www.auditboard.com",
    roles: ["quality", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=servicenow.com&sz=128",
    brand: "ServiceNow",
    name: "IT 与变更控制系统",
    description: "强大的数字化工作流平台，广泛应用于制药企业的 IT 服务管理 (ITSM) 和验证环境下的变更控制。",
    tags: ["变更管理", "ITSM", "工作流"],
    url: "https://www.servicenow.com",
    roles: ["it", "quality", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=talentlms.com&sz=128",
    brand: "TalentLMS",
    name: "在线培训管理系统",
    description: "轻量级且强大的 LMS 平台，非常适合生物制药企业进行 GxP 合规培训记录管理和员工考核。",
    tags: ["LMS", "培训管理", "合规"],
    url: "https://www.talentlms.com",
    roles: ["quality", "it", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=compliancequest.com&sz=128",
    brand: "ComplianceQuest",
    name: "合规质量管理平台",
    description: "基于 Salesforce 的企业级 QMS 和 EHS 平台，帮助生命科学企业实现自动化合规管理和风险管控。",
    tags: ["QMS", "EHS", "风险管理"],
    url: "https://www.compliancequest.com",
    roles: ["quality", "reg"],
  },

  // ==========================================
  // 2. 研发、生信与 AI (R&D, Bioinformatics & AI)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=schrodinger.com&sz=128",
    brand: "Schrödinger",
    name: "药物发现平台",
    description: "基于 AI 的计算化学平台，支持虚拟筛选、分子对接、ADMET 预测，显著加速小分子新药研发。",
    tags: ["AI", "药物发现", "计算化学"],
    url: "https://www.schrodinger.com",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=consensus.app&sz=128",
    brand: "Consensus",
    name: "AI 科学搜索引擎",
    description: "基于 AI 的科研搜索引擎，能够直接从数亿篇同行评审论文中提取科学结论，提供可靠的证据支持。",
    tags: ["AI", "科研搜索", "循证"],
    url: "https://consensus.app",
    roles: ["rd", "medical", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=scite.ai&sz=128",
    brand: "scite.ai",
    name: "智能引文分析平台",
    description: "通过 AI 分析引文的上下文，揭示研究成果是被支持、反驳还是仅仅被提及，提升文献调研的深度。",
    tags: ["AI", "文献调研", "引文分析"],
    url: "https://scite.ai",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=chatpdf.com&sz=128",
    brand: "ChatPDF",
    name: "AI 论文对话工具",
    description: "直接与 PDF 论文进行对话，快速提取核心观点、实验方法和结论，极大地提高阅读科研文献的效率。",
    tags: ["AI", "PDF处理", "文献阅读"],
    url: "https://www.chatpdf.com",
    roles: ["rd", "clinical", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=ncbi.nlm.nih.gov&sz=128",
    brand: "NCBI",
    name: "生物技术信息中心",
    description: "提供 BLAST、PubChem、Gene、GenBank 等最权威的生物信息学数据库及序列分析工具。",
    tags: ["生物信息", "数据库", "基因组学"],
    url: "https://www.ncbi.nlm.nih.gov",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=genecards.org&sz=128",
    brand: "GeneCards",
    name: "人类基因综合数据库",
    description: "全面的人类基因库，整合了转录组、蛋白质组及临床表型数据，是功能基因组学研究的核心工具。",
    tags: ["基因数据库", "生信分析", "RD"],
    url: "https://www.genecards.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=proteinatlas.org&sz=128",
    brand: "Protein Atlas",
    name: "人类蛋白质图谱",
    description: "提供人体所有主要组织和器官中蛋白质的表达分布信息，支持精准医疗与生物标志物发现。",
    tags: ["蛋白质组学", "组织分布", "医学研究"],
    url: "https://www.proteinatlas.org",
    roles: ["rd", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=depmap.org&sz=128",
    brand: "DepMap",
    name: "肿瘤依赖性图谱",
    description: "Broad Institute 开发的癌症依赖性门户，通过 CRISPR 和筛选数据揭示肿瘤细胞生存的关键基因。",
    tags: ["癌症研究", "靶点筛选", "CRISPR"],
    url: "https://depmap.org/portal/",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=thebiogrid.org&sz=128",
    brand: "BioGRID",
    name: "生物分子相互作用库",
    description: "一个精心策划的蛋白质、遗传和化学相互作用数据库，涵盖人类及主要模式生物。",
    tags: ["相互作用", "生信分析", "蛋白质组"],
    url: "https://thebiogrid.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pharos.nih.gov&sz=128",
    brand: "Pharos",
    name: "药物靶点光照门户",
    description: "NIH 资助的项目，旨在汇集、分级和展示关于潜在药物靶点的知识，重点关注未被充分研究的蛋白。",
    tags: ["靶点发现", "数据挖掘", "RD"],
    url: "https://pharos.nih.gov",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bindingdb.org&sz=128",
    brand: "BindingDB",
    name: "生物分子结合亲和力库",
    description: "一个公开可用的实测结合亲和力数据库，主要关注作为潜在药物靶点的蛋白质与类药小分子的相互作用。",
    tags: ["化学信息学", "结合亲和力", "药物发现"],
    url: "https://www.bindingdb.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=genenames.org&sz=128",
    brand: "HGNC",
    name: "基因命名委员会官网",
    description: "人类基因命名法权威资源，提供基因符号、全称及同义词映射，确保研究交流的一致性。",
    tags: ["基因命名", "标准化", "数据库"],
    url: "https://www.genenames.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=igv.org&sz=128",
    brand: "IGV",
    name: "交互式基因组浏览器",
    description: "Broad Institute 开发的经典基因组可视化工具，支持大规模组学数据（如 NGS）的流畅浏览与分析。",
    tags: ["基因组可视化", "NGS", "生信工具"],
    url: "https://software.broadinstitute.org/software/igv/",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=sanger.ac.uk&sz=128",
    brand: "COSMIC",
    name: "体细胞突变数据库",
    description: "全球最全面的癌症突变数据库，收录了人体癌症中体细胞突变的高质量手工策划信息。",
    tags: ["癌症基因组", "突变分析", "医学资源"],
    url: "https://cancer.sanger.ac.uk/cosmic",
    roles: ["rd", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=uniprot.org&sz=128",
    brand: "UniProt",
    name: "蛋白质知识库",
    description: "全球最全面的蛋白质序列和功能信息数据库，是蛋白质组学和靶点研究的核心资源。",
    tags: ["蛋白质", "数据库", "生命科学"],
    url: "https://www.uniprot.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=deepmind.com&sz=128",
    brand: "AlphaFold DB",
    name: "蛋白质结构预测数据库",
    description: "由 DeepMind 提供的开源蛋白质结构预测资源，助力药物靶点发现与蛋白质组学研究。",
    tags: ["AI", "蛋白质结构", "药物发现"],
    url: "https://alphafold.ebi.ac.uk",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=ebi.ac.uk&sz=128",
    brand: "ChEMBL",
    name: "生物活性化学分子数据库",
    description: "专注于具有类药特性的化学实体及其生物活性，是虚拟筛选和药理学研究的必备工具。",
    tags: ["化学数据库", "生物活性", "虚拟筛选"],
    url: "https://www.ebi.ac.uk/chembl/",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=opentargets.org&sz=128",
    brand: "Open Targets",
    name: "药物靶点鉴定平台",
    description: "整合基因、表型、药物和疾病关联数据，系统性地识别和优先排序候选药物靶点。",
    tags: ["靶点发现", "基因组学", "大数据"],
    url: "https://www.opentargets.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=string-db.org&sz=128",
    brand: "STRING",
    name: "蛋白相互作用网络",
    description: "蛋白-蛋白相互作用数据库，整合了已知及预测的物理、功能相互作用，支持复杂网络分析。",
    tags: ["蛋白质", "网络分析", "生信分析"],
    url: "https://string-db.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=genome.jp&sz=128",
    brand: "KEGG",
    name: "京都基因与基因组百科全书",
    description: "系统化了解基因通路、代谢网络及疾病药物关联，是生信功能注释的标准数据库。",
    tags: ["通路分析", "代谢", "生信分析"],
    url: "https://www.genome.jp/kegg/",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=rcsb.org&sz=128",
    brand: "PDB (RCSB)",
    name: "蛋白质结构数据库",
    description: "全球三维生物大分子结构的官方存储库，为结构生物学和药物设计提供核心坐标数据。",
    tags: ["三维结构", "蛋白质", "药物发现"],
    url: "https://www.rcsb.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=snapgene.com&sz=128",
    brand: "SnapGene",
    name: "分子生物学软件",
    description: "直观的质粒绘图、PCR 设计及序列比对工具，广泛用于分子克隆流程的记录与模拟。",
    tags: ["质粒设计", "分子克隆", "研发工具"],
    url: "https://www.snapgene.com",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=ensembl.org&sz=128",
    brand: "Ensembl",
    name: "基因组浏览器",
    description: "为脊椎动物及其他模式生物提供集成的基因组信息，支持序列查询、变异分析及比较基因组学。",
    tags: ["基因组", "生信分析", "数据库"],
    url: "https://www.ensembl.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=reactome.org&sz=128",
    brand: "Reactome",
    name: "生物通路数据库",
    description: "免费开源、同行评审的生物学通路和反应数据库，提供系统化的代谢与信号转导分析工具。",
    tags: ["通路分析", "代谢", "生信"],
    url: "https://reactome.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=swissmodel.expasy.org&sz=128",
    brand: "Swiss-Model",
    name: "蛋白质建模平台",
    description: "全自动的蛋白质结构同源建模服务器，广泛用于预测未知蛋白质的三维结构并评估其质量。",
    tags: ["蛋白质结构", "建模", "研发工具"],
    url: "https://swissmodel.expasy.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=expasy.org&sz=128",
    brand: "ExPASy",
    name: "生信资源入口",
    description: "由瑞士生物信息学研究所维护，整合了蛋白质组学、基因组学等领域的数百个工具和数据库入口。",
    tags: ["生信门户", "蛋白质组学", "工具集"],
    url: "https://www.expasy.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=metaboanalyst.ca&sz=128",
    brand: "MetaboAnalyst",
    name: "代谢组学分析平台",
    description: "综合性的代谢组学数据分析、可视化及功能解释平台，支持多种质谱和核磁共振原始数据。",
    tags: ["代谢组学", "数据分析", "生信工具"],
    url: "https://www.metaboanalyst.ca",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pubchem.ncbi.nlm.nih.gov&sz=128",
    brand: "PubChem Sketcher",
    name: "在线化学结构绘制",
    description: "PubChem 提供的在线化学结构编辑工具，支持绘制二维及三维分子结构，并导出多种化学格式。",
    tags: ["化学结构", "绘图工具", "分子设计"],
    url: "https://pubchem.ncbi.nlm.nih.gov/edit3/index.html",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=broadinstitute.org&sz=128",
    brand: "GSEA",
    name: "基因集富集分析工具",
    description: "Broad Institute 开发的计算方法，用于确定一组基因是否在不同的生物状态下显示出显著一致的差异。",
    tags: ["转录组学", "通路分析", "生信工具"],
    url: "https://www.gsea-msigdb.org/gsea/index.jsp",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=david.ncifcrf.gov&sz=128",
    brand: "DAVID",
    name: "生物信息学资源",
    description: "提供一整套功能注释工具，帮助研究人员理解大规模基因列表背后的生物学含义。",
    tags: ["功能注释", "富集分析", "生信分析"],
    url: "https://david.ncifcrf.gov/",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=galaxyproject.org&sz=128",
    brand: "Galaxy",
    name: "开放式生信分析平台",
    description: "基于 Web 的开源平台，支持 FAIR 数据处理、流程分析和可重复性研究，无需编程基础即可操作。",
    tags: ["开源平台", "生信分析", "工作流"],
    url: "https://galaxyproject.org/",
    roles: ["rd", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=huggingface.co&sz=128",
    brand: "Hugging Face",
    name: "AI 模型社区",
    description: "全球领先的开源模型库，包含针对蛋白质结构、基因序列和医疗文本预训练的 AI 模型。",
    tags: ["AI", "开源模型", "生信分析"],
    url: "https://huggingface.co",
    roles: ["rd", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pymol.org&sz=128",
    brand: "PyMOL",
    name: "分子可视化系统",
    description: "广泛使用的分子建模与展示工具，可生成出版级的高质量三维分子结构图。",
    tags: ["三维可视化", "蛋白质", "绘图工具"],
    url: "https://pymol.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=graphpad.com&sz=128",
    brand: "GraphPad Prism",
    name: "科研统计与绘图",
    description: "专为生物医学设计的统计分析工具，提供回归分析、t检验及专业的科学图表绘制。",
    tags: ["统计分析", "科学绘图", "RD工具"],
    url: "https://www.graphpad.com",
    roles: ["rd", "clinical"],
  },

  // ==========================================
  // 3. 监管、法规与标准 (Regulatory & Standards)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=nmpa.gov.cn&sz=128",
    brand: "NMPA",
    name: "中国国家药监局",
    description: "中国药品监管官方机构，发布药品注册申请指南、法规颁布及审评审批进度查询。",
    tags: ["监管", "指南", "官方"],
    url: "https://www.nmpa.gov.cn",
    roles: ["reg", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=fda.gov&sz=128",
    brand: "FDA",
    name: "美国食品药品监督管理局",
    description: "全球最具影响力的监管机构，提供药品准入指南、21 CFR 法规集及安全警示信息。",
    tags: ["监管", "FDA", "21 CFR"],
    url: "https://www.fda.gov",
    roles: ["reg", "quality", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=accessdata.fda.gov&sz=128",
    brand: "FDA Orange Book",
    name: "经评审批准药品目录",
    description: "权威的已获批药品及治疗等效性评价目录，是药企进行仿制药研发和知识产权调研的重要依据。",
    tags: ["药品目录", "仿制药", "FDA"],
    url: "https://www.accessdata.fda.gov/scripts/cder/ob/index.cfm",
    roles: ["reg", "rd", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=ema.europa.eu&sz=128",
    brand: "EMA",
    name: "欧洲药品管理局",
    description: "欧盟药品监管权威资源，提供集中审批程序、药物警戒指南及公共评估报告 (EPAR)。",
    tags: ["EMA", "欧盟法规", "监管"],
    url: "https://www.ema.europa.eu",
    roles: ["reg", "quality", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=cde.org.cn&sz=128",
    brand: "CDE",
    name: "NMPA 药审中心",
    description: "负责药品审评的核心部门，发布审评指导原则、受理公示、仿制药参比制剂等关键信息。",
    tags: ["审评", "指导原则", "注册申报"],
    url: "https://www.cde.org.cn",
    roles: ["reg", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=ich.org&sz=128",
    brand: "ICH",
    name: "人用药品注册技术协调会",
    description: "发布国际通用的 Q (质量)、S (安全)、E (有效性) 及 M (多学科) 药品注册技术指南。",
    tags: ["国际标准", "指南", "ICH"],
    url: "https://www.ich.org",
    roles: ["reg", "quality", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=cdisc.org&sz=128",
    brand: "CDISC",
    name: "临床数据标准协会",
    description: "提供全球公认的临床数据标准 (如 SDTM, ADaM)，确保临床试验数据的互操作性和监管提交合规性。",
    tags: ["数据标准", "临床试验", "提交规范"],
    url: "https://www.cdisc.org",
    roles: ["clinical", "reg", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=meddra.org&sz=128",
    brand: "MedDRA",
    name: "监管活动医学术语集",
    description: "由 ICH 开发的高标准医学术语分级体系，用于药物生命周期内安全性信息的分类和检索。",
    tags: ["医学术语", "PV", "合规标准"],
    url: "https://www.meddra.org",
    roles: ["pv", "clinical", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=ispe.org&sz=128",
    brand: "ISPE GAMP",
    name: "自动化制造实践指南",
    description: "生命科学行业公认的计算机化系统验证标准，提供 GAMP 5 指南以确保自动化系统的质量和合规。",
    tags: ["CSV", "验证标准", "合规指南"],
    url: "https://ispe.org/publications/guidance-documents/gamp-5",
    roles: ["quality", "it", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=usp.org&sz=128",
    brand: "USP",
    name: "美国药典",
    description: "提供权威的药品质量标准、参考标准品信息，是全球实验室分析和 QC 的重要依据。",
    tags: ["药典", "标准", "质量控制"],
    url: "https://www.usp.org",
    roles: ["quality", "production", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=edqm.eu&sz=128",
    brand: "Ph. Eur.",
    name: "欧洲药典 (EDQM)",
    description: "涵盖欧盟范围内原料药、制剂及生物制品的质量标准，保障欧洲药品的质量一致性。",
    tags: ["药典", "欧洲标准", "质量管理"],
    url: "https://www.edqm.eu",
    roles: ["quality", "production", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=nice.org.uk&sz=128",
    brand: "NICE",
    name: "英国国家医疗卓越研究所",
    description: "提供临床实践指南、健康技术评估 (HTA) 及市场准入的核心标准，是全球准入策略的重要参考。",
    tags: ["HTA", "临床指南", "市场准入"],
    url: "https://www.nice.org.uk",
    roles: ["reg", "medical", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=tga.gov.au&sz=128",
    brand: "TGA",
    name: "澳大利亚治疗用品管理局",
    description: "澳大利亚药品监管官方网站，提供最新的注册审批动态、法规指南及安全监管信息。",
    tags: ["监管", "澳大利亚", "法规"],
    url: "https://www.tga.gov.au",
    roles: ["reg", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=canada.ca&sz=128",
    brand: "Health Canada",
    name: "加拿大卫生部",
    description: "加拿大药品和医疗器械监管官方机构，提供授权产品查询及合规、质量、安全指南。",
    tags: ["监管", "加拿大", "法规"],
    url: "https://www.canada.ca/en/health-canada.html",
    roles: ["reg", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=picscheme.org&sz=128",
    brand: "PIC/S",
    name: "药品检查合作计划",
    description: "提供国际公认的 GMP 指南，是各国药监部门协调检查标准、提升质量管理的重要平台。",
    tags: ["GMP", "国际监管", "质量审计"],
    url: "https://picscheme.org/",
    roles: ["quality", "reg", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pmda.go.jp&sz=128",
    brand: "PMDA",
    name: "日本医药品医疗器械综合机构",
    description: "日本药品监管官方网站，提供最新的日本法规、审评报告及安全预警信息。",
    tags: ["日本市场", "监管", "法规"],
    url: "https://www.pmda.go.jp/english/",
    roles: ["reg", "quality", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=who.int&sz=128",
    brand: "WHO",
    name: "世界卫生组织",
    description: "提供全球公共卫生准则、基本药物清单、国际非专利名称 (INN) 及 GMP 规范。",
    tags: ["公共卫生", "基本药物", "全球标准"],
    url: "https://www.who.int",
    roles: ["reg", "medical", "clinical"],
  },

  // ==========================================
  // 4. 学术、文献与知识 (Academic & Literature)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=pubmed.ncbi.nlm.nih.gov&sz=128",
    brand: "PubMed",
    name: "生物医学文献搜索",
    description: "全球最重要的生命科学文献数据库，收录 Medline 海量期刊，是科研和医学事务必备入口。",
    tags: ["文献检索", "学术资源", "生物医学"],
    url: "https://pubmed.ncbi.nlm.nih.gov/",
    roles: ["rd", "clinical", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=europepmc.org&sz=128",
    brand: "Europe PMC",
    name: "欧洲生命科学文献库",
    description: "开放获取的生物医学文献库，整合了 PubMed 数据及专利、预印本，支持复杂的全文检索。",
    tags: ["开放获取", "文献检索", "生命科学"],
    url: "https://europepmc.org",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=protocols.io&sz=128",
    brand: "Protocols.io",
    name: "开放式实验方案平台",
    description: "领先的实验室方案共享和协作平台，支持动态调整方案步骤、记录评论并与同行分享最佳实践。",
    tags: ["实验协议", "方法分享", "协作"],
    url: "https://www.protocols.io",
    roles: ["rd", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bio-protocol.org&sz=128",
    brand: "Bio-protocol",
    name: "同行评审实验方案",
    description: "一个免费的、同行评审的在线方案期刊，旨在提高生命科学研究的可重复性，提供详细的步骤说明。",
    tags: ["实验方法", "可重复性", "学术资源"],
    url: "https://bio-protocol.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=connectedpapers.com&sz=128",
    brand: "Connected Papers",
    name: "科研论文知识图谱",
    description: "一种独特的视觉分析工具，通过图形化的方式展示论文之间的关联，帮助快速掌握领域研究脉络。",
    tags: ["引文分析", "科研导航", "论文检索"],
    url: "https://www.connectedpapers.com",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=researchrabbit.ai&sz=128",
    brand: "Research Rabbit",
    name: "科研论文智能雷达阵",
    description: "被誉为科研界的 Spotify，通过 AI 智能发现与你研究方向相关的文献，并建立个性化关联网络。",
    tags: ["AI", "文献追踪", "科研社交"],
    url: "https://www.researchrabbit.ai",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=lens.org&sz=128",
    brand: "The Lens",
    name: "全球专利与文献检索",
    description: "集成数亿条专利和学术论文数据，通过开放的链接和可视化工具揭示创新与科学之间的联系。",
    tags: ["专利检索", "文献调研", "创新分析"],
    url: "https://www.lens.org",
    roles: ["rd", "intelligence", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=dimensions.ai&sz=128",
    brand: "Dimensions",
    name: "科研链接数据平台",
    description: "整合了论文、资助项目、专利和临床试验的庞大数据库，支持多维度的科研影响力分析。",
    tags: ["科研大数据", "引文分析", "资助追踪"],
    url: "https://www.dimensions.ai",
    roles: ["rd", "intelligence", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=cnki.net&sz=128",
    brand: "中国知网 (CNKI)",
    name: "中文学术资源平台",
    description: "中国最大的学术文献库，涵盖期刊、硕博论文及行业标准，是查找国内医药研究的主要途径。",
    tags: ["中文论文", "学术资源", "文献检索"],
    url: "https://www.cnki.net/",
    roles: ["rd", "clinical", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=scholar.google.com&sz=128",
    brand: "Google Scholar",
    name: "全球学术搜索",
    description: "覆盖全球范围的学术论文、专利和书籍，支持引文追踪，是学术调研的强大搜索引擎。",
    tags: ["搜索引擎", "学术论文", "引文分析"],
    url: "https://scholar.google.com",
    roles: ["rd", "clinical", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=sciencedirect.com&sz=128",
    brand: "ScienceDirect",
    name: "Elsevier 文献平台",
    description: "提供高质量的同行评审文献，涵盖生命科学、健康科学等领域，支持全文获取。",
    tags: ["学术期刊", "文献", "生命科学"],
    url: "https://www.sciencedirect.com",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=webofscience.com&sz=128",
    brand: "Web of Science",
    name: "科学引文索引",
    description: "全球核心学术期刊索引，支持深度引文分析、影响因子查询及研究趋势追踪。",
    tags: ["SCI", "引文分析", "学术影响"],
    url: "https://webofscience.com",
    roles: ["rd", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=cochranelibrary.com&sz=128",
    brand: "Cochrane Library",
    name: "循证医学证据库",
    description: "提供高质量的系统评价和 Meta 分析，是临床决策和药物有效性评估的金标准。",
    tags: ["循证医学", "临床评价", "数据库"],
    url: "https://www.cochranelibrary.com",
    roles: ["clinical", "medical", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=zotero.org&sz=128",
    brand: "Zotero",
    name: "开源文献管理工具",
    description: "免费的文献收集、组织、引用工具，支持网页抓取和跨平台同步，极受科研人员喜爱。",
    tags: ["文献管理", "科研工具", "协作"],
    url: "https://www.zotero.org",
    roles: ["rd", "clinical", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=biorxiv.org&sz=128",
    brand: "bioRxiv",
    name: "生物学预印本平台",
    description: "在正式发表前分享生命科学领域的研究成果，是获取前沿学术动态的最快渠道。",
    tags: ["预印本", "学术前沿", "生物学"],
    url: "https://www.biorxiv.org",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=researchgate.net&sz=128",
    brand: "ResearchGate",
    name: "科研社交平台",
    description: "全球科研人员的交流社区，支持论文索取、学者网络建设与学术资源共享。",
    tags: ["学术交流", "科研社交", "论文共享"],
    url: "https://www.researchgate.net/",
    roles: ["rd", "clinical"],
  },

  // ==========================================
  // 5. 行业情报与资讯 (Industry Intelligence)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=pharmcube.com&sz=128",
    brand: "医药魔方",
    name: "医药数据专家",
    description: "专注于中国医药行业的深度数据分析、政策解读及投融资动态，提供精准的行业洞察。",
    tags: ["行业数据", "中国市场", "投融资"],
    url: "https://www.pharmcube.com",
    roles: ["intelligence", "market", "rd", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=yaozh.com&sz=128",
    brand: "药智网",
    name: "大健康数据平台",
    description: "提供药品注册、专利、一致性评价等全方位数据检索及行业资讯，助力研发决策。",
    tags: ["数据库", "注册申报", "行业资讯"],
    url: "https://www.yaozh.com",
    roles: ["intelligence", "reg", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=biospace.com&sz=128",
    brand: "BioSpace",
    name: "生物医药职场资讯",
    description: "不仅是全球生物技术和药企的人才招聘中心，也提供权威的行业快讯、临床进展及公司动态。",
    tags: ["职场招聘", "行业新闻", "药企动态"],
    url: "https://www.biospace.com",
    roles: ["intelligence", "market", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pharmavoice.com&sz=128",
    brand: "PharmaVoice",
    name: "制药领袖深度访谈",
    description: "专注于生命科学行业的企业战略、高管观点和市场趋势，从决策者视角剖析行业变革。",
    tags: ["企业战略", "行业趋势", "高管视角"],
    url: "https://www.pharmavoice.com",
    roles: ["intelligence", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=clarivate.com&sz=128",
    brand: "Cortellis",
    name: "医药情报数据库",
    description: "Clarivate 旗下的权威平台，涵盖研发管线、专利信息、交易数据及全球监管动态。",
    tags: ["医药情报", "专利", "研发管线"],
    url: "https://clarivate.com/products/biopharma/cortellis/",
    roles: ["intelligence", "market", "reg", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=iqvia.com&sz=128",
    brand: "IQVIA",
    name: "市场数据分析",
    description: "提供全球医药市场趋势、销售数据、处方分析及市场准入决策支持。",
    tags: ["市场数据", "咨询", "准入分析"],
    url: "https://www.iqvia.com",
    roles: ["intelligence", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=evaluate.com&sz=128",
    brand: "Evaluate",
    name: "商业评估与市场分析",
    description: "提供全球领先的医药市场预测数据、商业评估及管线价值分析，支持战略决策制定。",
    tags: ["商业评估", "预测数据", "战略"],
    url: "https://www.evaluate.com",
    roles: ["intelligence", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bioworld.com&sz=128",
    brand: "BioWorld",
    name: "生命科学商业快讯",
    description: "Clarivate 旗下的专业资讯平台，提供全球范围内新药研发、政策动态及公司策略的实时深度报道。",
    tags: ["行业新闻", "商业分析", "实时资讯"],
    url: "https://www.bioworld.com",
    roles: ["intelligence", "market", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=endpts.com&sz=128",
    brand: "Endpoints News",
    name: "全球生物医药资讯",
    description: "领先的生物技术新闻网站，提供深度报道、分析及全球行业高管的动态。",
    tags: ["行业新闻", "生物技术", "深度分析"],
    url: "https://endpts.com",
    roles: ["intelligence", "rd", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=fiercepharma.com&sz=128",
    brand: "Fierce Pharma",
    name: "制药行业动态",
    description: "涵盖药品研发、制造、营销及法规的实时新闻，是了解全球药企竞争态势的窗口。",
    tags: ["行业动态", "制药新闻", "市场分析"],
    url: "https://www.fiercepharma.com",
    roles: ["intelligence", "market", "production"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=fiercebiotech.com&sz=128",
    brand: "FierceBiotech",
    name: "生物技术行业快讯",
    description: "关注早期研发进展、投融资事件及全球生物技术公司的战略调整。",
    tags: ["生物技术", "研发快讯", "行业动态"],
    url: "https://www.fiercebiotech.com",
    roles: ["intelligence", "rd", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=statnews.com&sz=128",
    brand: "STAT News",
    name: "生命科学深度报道",
    description: "由资深记者主笔，专注于制药行业内幕、公共卫生政策及生命科学领域的深度报道。",
    tags: ["行业深度", "制药内幕", "政策资讯"],
    url: "https://www.statnews.com",
    roles: ["intelligence", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=biocentury.com&sz=128",
    brand: "BioCentury",
    name: "生物医药决策支持",
    description: "提供权威的战略分析、行业数据和资讯，专注于生物医药领域的投资与价值评估。",
    tags: ["战略分析", "行业资讯", "投资"],
    url: "https://www.biocentury.com/",
    roles: ["intelligence", "market", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pharmtech.com&sz=128",
    brand: "PharmTech",
    name: "制药技术与工艺资讯",
    description: "专注于药品制造、生物工艺、分析技术及质量控制的行业媒体，提供前沿的技术文章。",
    tags: ["制药工艺", "生产技术", "QC"],
    url: "https://www.pharmtech.com",
    roles: ["intelligence", "production", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=clinicaltrials.gov&sz=128",
    brand: "ClinicalTrials.gov",
    name: "全球临床试验登记库",
    description: "美国 NIH 运营，可查询全球竞品的临床进展、入组状态及方案细节。",
    tags: ["临床进展", "竞品分析", "数据库"],
    url: "https://clinicaltrials.gov",
    roles: ["clinical", "intelligence", "reg"],
  },

  // ==========================================
  // 6. 生产力与设计工具 (Productivity & Design)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=biorender.com&sz=128",
    brand: "BioRender",
    name: "生物医学绘图工具",
    description: "专业的在线插图绘制平台，提供海量生物医学图标，助力论文、方案及 PPT 演示。",
    tags: ["绘图", "插图", "学术演示"],
    url: "https://biorender.com",
    roles: ["rd", "medical", "market", "reg"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=miro.com&sz=128",
    brand: "Miro",
    name: "在线协作白板",
    description: "视觉化协作平台，非常适合跨部门团队进行流程梳理、研发项目规划及远程脑暴。",
    tags: ["团队协作", "流程图", "项目管理"],
    url: "https://miro.com",
    roles: ["all", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=figma.com&sz=128",
    brand: "Figma",
    name: "界面设计与原型",
    description: "基于云端的 UI/UX 设计工具，支持多人实时协作，适用于数字化平台界面设计与系统原型开发。",
    tags: ["UI设计", "产品设计", "协作工具"],
    url: "https://www.figma.com",
    roles: ["it", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=lucid.co&sz=128",
    brand: "Lucidchart",
    name: "在线流程图与图表",
    description: "强大的图表制作工具，支持绘制复杂的业务流程、系统架构及组织结构图，可与 Slack 等深度集成。",
    tags: ["流程图", "架构图", "生产力"],
    url: "https://lucid.app",
    roles: ["all", "it"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=undraw.co&sz=128",
    brand: "unDraw",
    name: "扁平化矢量插画库",
    description: "极简风格的开源矢量插画集合，色彩可在线自定义，非常适合提升 PPT 和数字化系统的现代感。",
    tags: ["插画", "素材", "PPT设计"],
    url: "https://undraw.co",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pexels.com&sz=128",
    brand: "Pexels",
    name: "高质免费素材库",
    description: "全球领先的免费版权图片和视频平台，素材风格现代且具有极高的专业审美，支持商用。",
    tags: ["免费摄影", "视频素材", "背景图"],
    url: "https://www.pexels.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=pixabay.com&sz=128",
    brand: "Pixabay",
    name: "创意资源社区",
    description: "拥有数百万张高质量的免费图片、插画和矢量图，是丰富 PPT 内容和网页设计的绝佳素材库。",
    tags: ["素材库", "插画", "免费商用"],
    url: "https://pixabay.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=coolors.co&sz=128",
    brand: "Coolors",
    name: "超快配色生成器",
    description: "极为便捷的配色方案设计工具，支持一键生成专业色板，确保 PPT 或系统界面颜色协调统一。",
    tags: ["配色设计", "UI工具", "审美提升"],
    url: "https://coolors.co",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=fontshare.com&sz=128",
    brand: "Fontshare",
    name: "专业免费字体库",
    description: "由印度字体基金会推出的高质量、免费且可商用的字体平台，提供多种风格的西文字体资源。",
    tags: ["西文字体", "设计资源", "免费商用"],
    url: "https://www.fontshare.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=adobe.com&sz=128",
    brand: "Adobe Express",
    name: "轻量级在线设计",
    description: "Adobe 旗下的快速设计工具，内置丰富的模板和字体，适合快速制作精美的海报、PPT 和社媒内容。",
    tags: ["在线设计", "模板", "多媒体"],
    url: "https://www.adobe.com/express/",
    roles: ["all", "market"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bioicons.com&sz=128",
    brand: "Bioicons",
    name: "免费科学图标库",
    description: "高质量、免费且开源的科学图标库，涵盖生化、细胞、分子等多个领域，支持 SVG 格式直接下载。",
    tags: ["图标库", "科研插图", "开源素材"],
    url: "https://bioicons.com",
    roles: ["rd", "medical", "market"],
  },
  {
    logo: "https://smart.servier.com/wp-content/themes/smart_v3/favicon.ico",
    brand: "Servier Medical Art",
    name: "专业医学图像素材",
    description: "提供超过 3000 个免费的医学矢量图像，涵盖解剖、细胞、器官、医疗设备等，非常适合制作 PPT 和海报。",
    tags: ["医学素材", "矢量图", "PPT插件"],
    url: "https://smart.servier.com",
    roles: ["rd", "medical", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=grammarly.com&sz=128",
    brand: "Grammarly",
    name: "AI 写作助手",
    description: "实时纠正英文论文、邮件及文档中的语法、拼写及风格错误，提升国际交流专业度。",
    tags: ["写作优化", "AI纠错", "英文助手"],
    url: "https://www.grammarly.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=deepl.com&sz=128",
    brand: "DeepL",
    name: "精准 AI 翻译",
    description: "基于人工神经网络的高质量翻译，尤其擅长处理医药专业术语，是跨国申报神器。",
    tags: ["翻译", "AI工具", "专业术语"],
    url: "https://www.deepl.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=notion.so&sz=128",
    brand: "Notion",
    name: "一体化协作空间",
    description: "集笔记、文档、项目管理和知识库于一体，适合构建团队 SOP 和资源索引中心。",
    tags: ["知识管理", "协作", "文档管理"],
    url: "https://www.notion.so",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=canva.cn&sz=128",
    brand: "Canva 可画",
    name: "在线平面设计平台",
    description: "海量 PPT 模板、海报及多媒体素材，支持零基础在线编辑，提升展示视觉质量。",
    tags: ["设计工具", "PPT模板", "素材"],
    url: "https://www.canva.cn",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=processon.com&sz=128",
    brand: "ProcessOn",
    name: "在线流程图工具",
    description: "支持流程图、思维导图、组织结构图，便于团队协作绘制实验流程或业务逻辑。",
    tags: ["流程图", "思维导图", "协作"],
    url: "https://www.processon.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=paperpile.com&sz=128",
    brand: "Paperpile",
    name: "现代文献管理插件",
    description: "基于 Google Drive 的轻量级文献管理，支持一键保存论文、PDF 批注及引用插入。",
    tags: ["文献管理", "科研工具", "浏览器插件"],
    url: "https://paperpile.com/",
    roles: ["rd", "medical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=slidesgo.com&sz=128",
    brand: "Slidesgo",
    name: "PPT 模板资源",
    description: "专注于教育、科研、医疗领域的 PPT 模板库，风格精美且支持 Google Slides/PowerPoint。",
    tags: ["PPT模板", "学术演示", "免费资源"],
    url: "https://slidesgo.com",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=iconfont.cn&sz=128",
    brand: "IconFont",
    name: "阿里矢量图标库",
    description: "中国最大的矢量图标库，提供丰富的科学、医学类图标，支持 SVG/PNG 格式下载。",
    tags: ["图标", "素材", "设计"],
    url: "https://www.iconfont.cn",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=remove.bg&sz=128",
    brand: "Remove.bg",
    name: "图片抠图工具",
    description: "利用 AI 一键自动去除图片背景，适合快速处理科研插图或人物头像。",
    tags: ["图片处理", "AI工具", "抠图"],
    url: "https://www.remove.bg",
    roles: ["all"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=slack.com&sz=128",
    brand: "Slack",
    name: "团队协作通讯平台",
    description: "高效的即时通讯工具，支持丰富的插件集成，加速研发与生产的跨部门协作。",
    tags: ["协作", "即时通讯", "IT工具"],
    url: "https://slack.com",
    roles: ["it", "rd"],
  },

  // ==========================================
  // 7. 实验试剂与设备 (Reagents & Equipment)
  // ==========================================
  {
    logo: "https://www.google.com/s2/favicons?domain=thermofisher.com&sz=128",
    brand: "Thermo Fisher",
    name: "赛默飞世尔科技",
    description: "全球科学服务巨头，提供涵盖细胞培养、基因测序、质谱分析的一站式仪器与试剂。",
    tags: ["实验室仪器", "试剂", "生命科学"],
    url: "https://www.thermofisher.com",
    roles: ["rd", "production", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=illumina.com&sz=128",
    brand: "Illumina",
    name: "基因测序领航者",
    description: "全球高通量测序 (NGS) 技术的领导者，提供先进的测序 platform 及生信分析流程，加速精准医疗研究。",
    tags: ["基因测序", "NGS", "生信分析"],
    url: "https://www.illumina.com",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=qiagen.com&sz=128",
    brand: "QIAGEN",
    name: "样本与测序专家",
    description: "提供高质量的样本制备、测序试剂及生物信息学解读工具，广泛用于分子诊断和生物研究。",
    tags: ["样本处理", "分子诊断", "生信工具"],
    url: "https://www.qiagen.com",
    roles: ["rd", "clinical"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bd.com&sz=128",
    brand: "BD",
    name: "碧迪医疗",
    description: "全球领先的流式细胞术、临床检测及医疗设备供应商，在肿瘤免疫和血液学研究中具有核心地位。",
    tags: ["流式细胞", "医疗器械", "临床检测"],
    url: "https://www.bd.com",
    roles: ["rd", "clinical", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=beckmancoulter.com&sz=128",
    brand: "Beckman Coulter",
    name: "贝克曼库尔特",
    description: "提供先进的离心机、颗粒分析仪及实验室自动化解决方案，广泛应用于生产质控与生物分析。",
    tags: ["实验室自动化", "离心机", "质量控制"],
    url: "https://www.beckmancoulter.com",
    roles: ["production", "quality", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bio-techne.com&sz=128",
    brand: "Bio-Techne",
    name: "生物试剂供应商",
    description: "提供高质量的重组蛋白、抗体、ELISA 试剂盒及 R&D Systems 品牌下的各种细胞因子。",
    tags: ["重组蛋白", "抗体", "试剂"],
    url: "https://www.bio-techne.com",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=zeiss.com&sz=128",
    brand: "Zeiss",
    name: "蔡司光学与显微镜",
    description: "全球顶尖的光学技术与显微成像解决方案提供商，涵盖激光共聚焦、电子显微镜等前沿科研设备。",
    tags: ["显微镜", "光学成像", "科研设备"],
    url: "https://www.zeiss.com/microscopy/",
    roles: ["rd", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=leica-microsystems.com&sz=128",
    brand: "Leica",
    name: "徕卡显微系统",
    description: "专注于精密光学显微镜、成像系统及样本处理，为生命科学、医疗诊断及工业质检提供专业支持。",
    tags: ["成像系统", "显微技术", "样本制备"],
    url: "https://www.leica-microsystems.com",
    roles: ["rd", "clinical", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=agilent.com&sz=128",
    brand: "Agilent",
    name: "安捷伦科技",
    description: "领先的分析仪器供应商，在液相色谱 (HPLC)、气相色谱 (GC) 领域具有行业领导地位。",
    tags: ["分析仪器", "色谱", "质量控制"],
    url: "https://www.agilent.com",
    roles: ["quality", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=waters.com&sz=128",
    brand: "Waters",
    name: "沃特世科技",
    description: "专注于液相色谱与质谱技术，提供专业的分析方法验证系统及 Empower 数据平台。",
    tags: ["液相色谱", "质谱", "方法验证"],
    url: "https://www.waters.com",
    roles: ["quality", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=merckmillipore.com&sz=128",
    brand: "Merck Millipore",
    name: "默克生命科学",
    description: "提供先进的生物工艺解决方案，尤其在过滤、纯化及清洁验证领域具有深厚技术积累。",
    tags: ["过滤", "纯化", "生物工艺"],
    url: "https://www.merckmillipore.com",
    roles: ["production", "quality", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=sartorius.com&sz=128",
    brand: "赛多利斯",
    name: "生物工艺专家",
    description: "提供从细胞培养到一次性生物反应器的全面流程方案，助力生物药工艺放大与生产。",
    tags: ["生物反应器", "一次性技术", "生产"],
    url: "https://www.sartorius.com",
    roles: ["production", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=cytiva.com&sz=128",
    brand: "Cytiva (原 GE 医疗)",
    name: "思拓凡生命科学",
    description: "提供层析系统、纯化填料及波浪式生物反应器，是生物制药下游工艺的核心供应商。",
    tags: ["层析", "纯化", "生物工艺"],
    url: "https://www.cytiva.com",
    roles: ["production", "rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=eppendorf.com&sz=128",
    brand: "Eppendorf",
    name: "实验室精密仪器",
    description: "全球领先的移液系统、离心机及细胞处理耗材供应商，以极致的精密性和可靠性著称。",
    tags: ["移液系统", "离心机", "实验室耗材"],
    url: "https://www.eppendorf.com",
    roles: ["rd", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=neb.com&sz=128",
    brand: "NEB",
    name: "纽英伦生物技术",
    description: "全球分子生物学酶和试剂的标杆，提供高品质的限制酶、聚合酶及 DNA 修饰工具。",
    tags: ["分子生物学", "酶制剂", "实验室试剂"],
    url: "https://www.neb.com",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=bio-rad.com&sz=128",
    brand: "Bio-Rad",
    name: "伯乐生命科学",
    description: "提供涵盖电泳、数字 PCR、蛋白印迹及分析仪器的全面生命科学 research 解决方案。",
    tags: ["生命科学仪器", "PCR", "分析"],
    url: "https://www.bio-rad.com",
    roles: ["rd", "quality"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=abcam.com&sz=128",
    brand: "Abcam",
    name: "全球抗体专家",
    description: "拥有经过验证的高质量抗体、试剂盒及检测平台，支持肿瘤、免疫等领域的深入研究。",
    tags: ["抗体", "试剂盒", "生命科学"],
    url: "https://www.abcam.com",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=medchemexpress.cn&sz=128",
    brand: "MCE",
    name: "小分子抑制剂平台",
    description: "提供海量的抑制剂、激动剂及化合物库，广泛应用于新药筛选和药理机制研究。",
    tags: ["抑制剂", "化合物库", "新药筛选"],
    url: "https://www.medchemexpress.cn",
    roles: ["rd"],
  },
  {
    logo: "https://www.google.com/s2/favicons?domain=wuxibiologics.com&sz=128",
    brand: "药明生物",
    name: "一体化 CDMO 平台",
    description: "全球领先的生物制药赋能平台，提供从发现到商业化生产的端到端 CRDMO 解决方案。",
    tags: ["CDMO", "生物药", "外包服务"],
    url: "https://www.wuxibiologics.com",
    roles: ["rd", "production"],
  },
];
